name: 'Enforce conventional messages on all commits push'

on: [ push, pull_request ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: enforce-commit-msg-style
        uses: webiny/action-conventional-commits@v1.2.0
